name: smartqueue_staff_app
description: Tsehay Bank smart queue app for staff and customers.
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  signature: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tsehay_logo.png
